// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Lrc0fKeY2Tc542_vvMtNOCKP7XpxcKc',
    appId: '1:909358236610:android:d4ec939a5dfaa5401fcc5b',
    messagingSenderId: '909358236610',
    projectId: 'ajhub-e1a21',
    storageBucket: 'kadam-investment.firebasestorage.app', // Corrected value
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-QFMUhNk7QYFZFIGmRbTd8fnN5uVhrIg',
    appId: '1:40782785503:ios:your_ios_app_id',
    messagingSenderId: '40782785503',
    projectId: 'elpoir-salon-and-beauty-5e22b',
    storageBucket: 'elpoir-salon-and-beauty-5e22b.firebasestorage.app',
    iosClientId: 'your_ios_client_id.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.elpoirbeautymanager',
  );

// Add any other platforms (e.g., Web, macOS) if needed.
}
